#!/bin/zsh

set-tokens
# get model list

fetch_models() {
    curl -s https://api.githubcopilot.com/models \
        -H "Authorization: Bearer $OPENAI_API_KEY" \
        -H "Content-Type: application/json" \
        -H "Copilot-Integration-Id: vscode-chat"
}

output=$(fetch_models)

if [ $? -ne 0 ]; then
    set-tokens refresh
    output=$(fetch_models)
fi

echo "$output" | jq -r ".data[] | select(.model_picker_enabled == true) | .id"
