#!/bin/zsh

# __fzf_list_hosts() {
#   local hosts=($(awk '/^Host / && $2 !~ /^\*/ {print $2}' ~/.ssh/config.custom))
#   hosts+=($(awk '!/rdev/ && !/k8s/ && /^[[:alpha:]]/ {print $1}' ~/.ssh/known_hosts))
#   echo $hosts | tr ' ' '\n' | sort -u
# }

fssh() {
  # Fuzzy search through SSH hosts and establish SSH connection
  # Usage: fssh [hostname]
  # If hostname is provided, connects directly
  # Otherwise, opens fuzzy finder to select from available hosts
  
  local target_host
  
  if [[ $# -eq 1 ]]; then
    target_host="$1"
  else
    target_host="$(__fzf_list_hosts | fzf)" || return 0
  fi

  [[ -z "$target_host" ]] && return 0

  echo -e "$target_host" | tmux-create-panes -c "TERM=xterm-color command ssh"

#fssh "$@"
