#!/bin/zsh

nvim_conf_switcher() {
  local selection
  selection=$(fd --type=d "vim" ~/.config --exec basename | fzf --prompt="Select config > " --ghost='Pick nvim config…' --border-label="  Neovim Config Switcher ")
  [[ -z "$selection" ]] && return 0
  NVIM_APPNAME=$selection nvim "$@"
}
