#!/bin/zsh

nvim_conf_switcher() {
  selection=$(fd --type=d "vim" ~/.config --exec basename | fzf --prompt="Select config > "  --border-label="  Neovim Config Switcher ")
  NVIM_APPNAME=$selection nvim $@
}
