#!/bin/zsh

typeset -a light_themes=(
    dawnfox
    dayfox
    everforest
    gruvbox-material
    tokyonight-day
)
typeset -a dark_themes=(
    everforest
    gruvbox-material
    nightfox
    nordfox
    tokyonight-moon
    tokyonight-night
    tokyonight-storm
)

bg_mode=$(cat /tmp/.bg_mode 2>/dev/null | tr -d "[:space:]")
theme_var="${bg_mode}_themes"
selected_theme=$(printf '%s\n' "${(P@)theme_var}" | fzf --prompt="Select theme: ")

# Exit if no theme selected (user pressed ESC or Ctrl+C)
if [[ -z "$selected_theme" ]]; then
    echo "No theme selected. Exiting....."
    return 1
fi

# echo "$selected_theme" > /tmp/theme
echo "$selected_theme" > "/tmp/.theme_${bg_mode}"

source ~/scripts/theme-switcher
