# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
prSections:
- title: My Created
  filters: is:open author:@me sort:updated-desc

- title: For Review (Autobuild)
  filters: >-
    is:open review-requested:@me 
    repo:linkedin-multiproduct/autobuild 
    repo:linkedin-multiproduct/lipy-autobuild-db 
    repo:linkedin-multiproduct/lipy-autobuild-daemon-base
    repo:linkedin-multiproduct/lipy-autobuild-common
    repo:linkedin-multiproduct/build-orchestrator
  type: null

- title: For Review (All)
  filters: is:open review-requested:@me
  type: null

# - title: Involved
#   filters: is:open involves:@me -author:@me
#   type: null

issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 60
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: 
    - key: g
      name: open lazygit
      command: >
        cd {{.RepoPath}} && lazygit
  issues: []
  prs:
    - key: n
      name: open repo in nvim
      command: >
        cd {{.RepoPath}} && nvim
    - key: C
      name: review pr
      command: >
        tmux new-window -c {{.RepoPath}} '
        nvim -c ":silent Octo pr edit {{.PrNumber}}"'
  branches: []
repoPaths:
  linkedin-multiproduct/*: "~/development/work/multiproducts/*"
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: "delta"
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: false
