#!/usr/bin/env bash

read -r theme bg_mode < <(get-theme)
echo "Switching to theme: $theme with background mode: $bg_mode"

# Update neovim load_colorscheme
nvr --serverlist | xargs -I {} nvr --servername {} -c "lua Load_colorscheme();" 

# Update tmux theme
if [[ -n $TMUX ]]; then
  tmux-theme-switcher "$theme" 2> /dev/null
fi

# update delta theme
declare -A special_themes=(
  ["everforest"]=1
  ["gruvbox"]=1
  ["gruvbox-material"]=1
)
if [[ -v special_themes["$theme"] ]]; then
    theme="${theme}-${bg_mode}"
fi

sd '^(\s*features\s*=).*$' "\$1 ${theme}" "$HOME"/.delta-gitconfig

# update delta bg_mode in lazygit
sd '(pager: delta[^"]*?)(?: --(light|dark))?([^"]*")' "\$1 --${bg_mode}\$3" "$HOME"/.config/lazygit/config.yml
