#!/bin/bash

background_mode=$(cat /tmp/.bg_mode 2>/dev/null | tr -d "[:space:]")

selected_theme="${1:-$(cat /tmp/.theme_${background_mode} 2>/dev/null | tr -d "[:space:]")}"
selected_theme="${selected_theme:-gruvbox-material}"

echo "Switching to theme: $selected_theme with background mode: $background_mode"

# Update neovim load_colorscheme
nvr --serverlist | xargs -I {} nvr --servername {} -c "lua Load_colorscheme();"

# Source fzf configuration
# source ~/fzf-themes/${selected_theme}.sh
source ~/fzf_config.zsh

# Update tmux theme
tmux-theme-switcher "$selected_theme" 2> /dev/null
# tmux source-file ~/.tmux.conf

# update lazygit theme
sd 'pager: (.*) --\w+$' "pager: \$1 --${background_mode}" $HOME/.config/lazygit/config.yml
